apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  labels:
    app: postgres-db-service
    name: tasks-tracker-app

spec:
  selector:
    name: postgres-db-pod
    app: tasks-tracker-app
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
  