apiVersion: v1
kind: Pod
metadata:
  name: backend-spring-pod
  labels:
    name: backend-spring-pod
    app: tasks-tracker-app
spec:
  containers:
    - name: backend-spring
      image: tasks-tracker
      ports:
        - containerPort: 8080
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: changeme
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-db-service:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: changeme
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update