apiVersion: v1
kind: Service
metadata:
  name: backend-spring-service
  labels:
    app: backend-spring-service
    name: tasks-tracker-app

spec:
  selector:
    name: backend-spring-pod
    app: tasks-tracker-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  type: NodePort
  